services:
  - type: web
    name: othello-meister
    runtime: node
    buildCommand: npm install && cd server && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
